### ISSUE TITLE
[reconnection service] add full public facing readme

### ISSUE THREAD

**Issue by p5150j** [AmplicaLabs/reconnection-service#31]
Currently, we have some diagrams and a description of the reconnection service in the readme. 

What we want to add is more technical sections of the readme to:

- [ ] understand the parts and pieces of how the code works and is structured 
- [ ] the use of graphSDK
- [ ] running the docker container locally, on a VM etc
- [ ] running the service without docker if they so choose
- [ ] basic docs on functions and methods that make this service work
- [ ] other...

**Comment by wilwade** [comment]
@JoeCap08055 We should likely link the Install from the Readme and perhaps add some context headers/text around the diagrams

**Comment by JoeCap08055** [comment]
> @JoeCap08055 We should likely link the Install from the Readme and perhaps add some context headers/text around the diagrams

New PR #65
