### ISSUE TITLE
[reconnection-service] Add Capacity cap

### ISSUE THREAD

**Issue by JoeCap08055** [AmplicaLabs/reconnection-service#41]
As a user, I want to make sure that the reconnection service cannot use more than a configured amount of Capacity per epoch.

The amount of capacity to use should be able to be specified either as a fixed amount of Capacity, or as a percentage of the provider's total Capacity.

**Comment by saraswatpuneet** [comment]
TODO: Testing remains to check if capacity falls below the queue must pause
