### ISSUE TITLE
Review testing endpoints and choose what we want in prod 

### ISSUE THREAD

**Issue by p5150j** [AmplicaLabs/reconnection-service#63]
A number of endpoints were created during development for assistance in testing. Review the following endpoints to determine which (if any) should be promoted to production.

Also, to be determined: do we want/need to set up any kind of security around these endpoints if they are promoted to production?

|Endpoint|Method|Parameters|Description|
|-|-|-|-|
|`dev/queue/clear`|`POST`| |Clear all pending, completed, and failed jobs from the queue|
|`dev/queue/remove`|`POST`|`jobId`|Remove the identified job from the queue|
|`dev/queue/pause`|`POST`| |Pause the queue|
|`dev/queue/resume`|`POST`| |Resume the queue|
|`dev/queue/retry`|`POST`|`jobId`|Manually retry the indicated job|
|`dev/queue/update`|`POST`|JSON payload:<br/>`{"dsnpId": string,"providerId": string,"processTransitiveUpdates": boolean}`|Update the indicated job with the payload|
|`dev/queue`|`POST`|JSON payload:<br/>`{"dsnpId": string,"providerId": string,"processTransitiveUpdates": boolean}`|Add the job to the queue||`dev/queue`|`POST`|JSON payload:<br/>`{"dsnpId": string,"providerId": string,"processTransitiveUpdates": boolean}`|Add the job to the queue|
|`dev/update/graph`|`POST`|JSON payload:<br/>`{"dsnpId": string,"providerId": string,"processTransitiveUpdates": boolean}`|Process the indicated user graph update immediately, bypassing the job queue|
|`dev/scan/:blockNumber`|`POST`|`blockNumber`|Initiate a blockchain scan starting from the indicated block number|
|`dev/scan`|`POST`| |Initiate a blockchain scan starting from the last-scanned block number|

**Comment by saraswatpuneet** [comment]
The following seem redundant or questionable from user privacy perspective, I think we should rely on chain to  add a job to the queue following the events; instead of outside source manipulating the queue, 

there are apis to rollback scanner to a block in past and re-scan, flush the queue to start from scratch etc. in case someone wants to update state

Thoughts? @wilwade  @JoeCap08055 

dev/queue/update | POST | JSON payload:{"dsnpId": string,"providerId": string,"processTransitiveUpdates": boolean} | Update the indicated job with the payload
-- | -- | -- | --
dev/queue | POST | JSON payload:{"dsnpId": string,"providerId": string,"processTransitiveUpdates": boolean} | Add the job to the queue
dev/update/graph | POST | JSON payload:{"dsnpId": string,"providerId": string,"processTransitiveUpdates": boolean} | Process the indicated user graph update immediately, bypassing the job queue

**Comment by wilwade** [comment]
@saraswatpuneet That sounds reasonable to me

**Comment by JoeCap08055** [comment]
> The following seem redundant or questionable from user privacy perspective, I think we should rely on chain to add a job to the queue following the events; instead of outside source manipulating the queue,
> 
> there are apis to rollback scanner to a block in past and re-scan, flush the queue to start from scratch etc. in case someone wants to update state
> 
> Thoughts? @wilwade @JoeCap08055
> 
> dev/queue/update	POST	JSON payload:{"dsnpId": string,"providerId": string,"processTransitiveUpdates": boolean}	Update the indicated job with the payload
> dev/queue	POST	JSON payload:{"dsnpId": string,"providerId": string,"processTransitiveUpdates": boolean}	Add the job to the queue
> dev/update/graph	POST	JSON payload:{"dsnpId": string,"providerId": string,"processTransitiveUpdates": boolean}	Process the indicated user graph update immediately, bypassing the job queue

I agree; I just wanted to put them up for review. So then are we going to move all of the GET endpoints to the production controller? And what about the other queue manipulation endpoints (pause/resume/clear)?

**Comment by wilwade** [comment]
@JoeCap08055 / @saraswatpuneet 

If we think of the env vars as a stateless way to do the same thing, if there is a queue issue, someone could just clear it via the state.

Perhaps this: An env var that enables or disables all endpoints (default disabled). Then it is just up to the user to manage it directly.

**Comment by JoeCap08055** [comment]
All of these endpoints are already selectively enabled/disabled by `ENABLE_DEV_CONTROLLER` (boolean) env var

**Comment by wilwade** [comment]
> All of these endpoints are already selectively enabled/disabled by `ENABLE_DEV_CONTROLLER` (boolean) env var

Then it sounds like it is just a documentation issue! (Perhaps a rename?)

**Comment by JoeCap08055** [comment]
I guess the issue was do we want to promote any of those "dev" endpoints to prod (ie, not toggled by the env var)? That would simply entail moving them into the other controller file. If not, we'll simply use this issue to update the docs and call it a day.

**Comment by wilwade** [comment]
It is good. Let's update the docs and ship it
